### ISSUE TITLE
Support for SAML

### ISSUE THREAD

**Issue by bcoe** [npm/npmo-installer#102]
We would like to add support for SAML to npm On-Site, some of the required work is broken out below:

- [x] test the SAML flow manually in Node.js:
  * https://www.npmjs.com/package/saml2-js looks like a promising library.
  * https://www.onelogin.com/ seems like a good service for testing the initial flow.
- [x] build a landing page for SAML/OAuth style flows in npm On-Site:
  * what do we store to identify the SAML session (I think we'll probably be able to fetch something like an access token, I think they're called `claims` in SAML speak).
- [x] test the plugin with a real-world SAML deployment.

@kevinSuttle, @nexdrew

**Comment by kevinSuttle** [comment]
:boom:

**Comment by bcoe** [comment]
@kevinSuttle I'm started doing some initial hacking on a SAML auth strategy, a couple questions:

1. can the SAML authentication system that you authenticate against behind the firewall make requests back out to external applications? We would need a user to:
  i. VPN into servers that have access to your SAML server.
  ii. run the login dance.
  iii. have the SAML server make a request out to the external npm On-Site server.
2. would you be able to screen share and test authentication against your SAML server?

**Comment by bcoe** [comment]
Thought about the login flow:

* a new bin is provided for logging in via SAML (this bin could later be extended to support other SSO flows).
* when logging in a user would immediately be issued a token for their `.npmrc`, and then be directed out to the SAML flow.
* when the SAML flow phoned home to a page on On-Site, the email from callback would be matched up with the email that a user entered during the npm login step.
* a user would not be allowed to publish or install scoped modules from the on-site server until the email had been confirmed via this SAML dance.

**Comment by kevinSuttle** [comment]
Pretty much wrapped up, yes? Nice work, btw!

**Comment by bcoe** [comment]
@kevinSuttle we're most of the way there, I have one more usability patch that should go out within the next day or so.

You will no longer need to run npm with `--verbose`, it will instead exit immediately with a better error message.

I'll close this ticket once the update goes out the door.

**Comment by kevinSuttle** [comment]
:+1: Thanks, Ben.

**Comment by bcoe** [comment]
<img width="749" alt="screen shot 2016-01-11 at 2 56 50 pm" src="https://cloud.githubusercontent.com/assets/194609/12249306/bdb850c6-b873-11e5-9afb-364d3d4200e8.png">

Okay, that's looking good -- will get this pulled in today.

**Comment by kevinSuttle** [comment]
:tada:
