### ISSUE TITLE
Allow customized placement of the promoted packages

### ISSUE THREAD

**Issue by marcellodesales** [npm/npmo-installer#113]
The current placement of the promoted modules is static on the main Search site. We'd like a better alternative to help promoting our internal modules based on different requirements.

<img width="1224" alt="screen shot 2016-01-12 at 12 29 04 pm" src="https://cloud.githubusercontent.com/assets/131457/12276039/451570e4-b928-11e5-90f4-cf8c14ac849f.png">

Requirements
-------

* Our Enteprise would like to make decisions over which modules are placed in the promoted area, specially having our own brand. For instance, a selected number of modules displayed with their own logo (described by #112).

* Our Enterprise would like to have a different mix of placement strategies such as random, static, rotational over time, etc.

* (HOW) The selection of which modules to display should be as simple as updating a private Git repository so that it is easily broadcasted to all different data centers.

* Allow to increase or decrease the number of rows from the static 5.

**Comment by kevinSuttle** [comment]
Big +1 here.

**Comment by marcellodesales** [comment]
@kevinSuttle yeah, waiting on NPM to comment on this because this is an ask from higher-up managers in our company...

**Comment by nexdrew** [comment]
@marcellodesales @kevinSuttle This is definitely a high priority on our current roadmap. I can't give you a delivery date, but please know that we are aware of this feature request and will be working on it soon.

**Comment by marcellodesales** [comment]
@nexdrew Thanks a lot for letting us know :+1: Will be waiting... :)

**Comment by bcoe** [comment]
@marcellodesales @kevinSuttle we discussed this in our weekly planning today, it's sneaking up to the top of our roadmap.

**Comment by marcellodesales** [comment]
@bcoe awesome to know! Keep us posted!

**Comment by bcoe** [comment]
This feature is now released, there's a bin that gets installed during default install process now:

https://github.com/npm/npm-explicit-installs

On an existing installation you can run:

```
sudo npm i npmo -g --ignore-scripts
```

This will introduce the new command:

```
npmo edit-homepage
```

**Comment by kevinSuttle** [comment]
Ok, tested the commands. 

Some feedback: referencing scope is awkward. The package I had previously published is gone, yet the `add` command added an empty package anyway. 

![https://cldup.com/dvIJq8W8EX.png ](https://cldup.com/dvIJq8W8EX.png )
<img width="1414" alt="npm_ _ibm" src="https://cloud.githubusercontent.com/assets/95672/12855672/be41602e-cc0e-11e5-8b13-d05b7f05c1ac.png">

Would be nice to see which ones I've published and choose from those, much like the ones that appear during the `delete` command

<img width="541" alt="screen shot 2016-02-04 at 5 26 39 pm" src="https://cloud.githubusercontent.com/assets/95672/12855648/947a84f0-cc0e-11e5-9c9e-8d09edc1ccd2.png">

=== 

I also expected a the ~75% of the page to be specific to my org. Like, the same categories and layout as the public npm, but with our packages. Is that possible?

**Comment by marcellodesales** [comment]
@bcoe For those using NPMO using docker and docker-compose, how should I use this? Do I need to install `npmo` and run the command?

**Comment by marcellodesales** [comment]
Here's how I'm keepting our site updated... 

1. Downloaded the `packages.json` and `logos.json` from the newww and store them in the `patches` directory where they can be version-controlled.
2. Execute the commands from the script below and keep the website updated...

```
######
##
## Updates the featured packages displayed in the website.
##
## 1. Update the list at patches/newww/featured-packages/packages.json
## 2. In order for logos to be displayed, make sure the module added has:
## - package.json has a field "logo", pointing to the URL of an image (can be any size), 144x144 suggested
## - the file patches/newww/featured-packages/logos.json has a matching entry to the logo.
## 3. Execute this script while ALL the containers are running
## 
## TODO: Ben from NPM suggested using chokidar for automatic updates in the FS
## TODO: Marcello from Intuit suggested using webhooks for a given repo and update
## 
docker cp patches/newww/featured-packages/packages.json npmoserver_newww_1:/etc/npme/data/npm-explicit-installs/packages.json
docker cp patches/newww/featured-packages/logos.json npmoserver_newww_1:/etc/npme/data/npm-explicit-installs/logos.json
docker exec -ti npmoserver_newww_1 /etc/npme/data/npm-explicit-installs/bin/npm-explicit-installs.js bust-cache
```

<img width="1140" alt="screen shot 2016-02-23 at 10 03 51 am" src="https://cloud.githubusercontent.com/assets/131457/13261457/018dce76-da15-11e5-9b58-34c563d88d89.png">
