### ISSUE TITLE
fully automated install

### ISSUE THREAD

**Issue by mcqueenorama** [npm/npmo-installer#68]
We need to be able to install without the setup dialogue.  We need to be able to specify license info, and couchdb url info, and perhaps more, all install config items, without user intervention.  Currently its user email, license, interrupt to specify couchdb tarball, edit config at the end to add couchdb url parms and read-through-cache urls, and auth=false.

**Comment by bcoe** [comment]
Installing npm On-Site is now as simple as:

`npm install npmo -g --unsafe`
