### ISSUE TITLE
Unmet license requirement: Please click here to add 1 additional host

### ISSUE THREAD

**Issue by taylorc93** [npm/npmo-installer#79]
Hi!

I've been trying to set up my company's on site NPM registry.  I've run `sudo npm install npmo-installer -g --unsafe` and it seems like everything worked out (I got the success message after running that command).  However, when I access the management console, I see this:

<img width="1364" alt="screen shot 2015-09-24 at 1 08 13 pm" src="https://cloud.githubusercontent.com/assets/3298791/10080384/618487f4-62bd-11e5-9fc1-4558578a6e9d.png">

I've searched through your documentation, watched the getting started video, and tried configuring a host  through the hosts tab but I'm lost about what I need to do to fix this.  Can you provide some instructions on how to resolve this?

**Comment by bcoe** [comment]
@taylorc93 it's most likely that the installer was unable to find `eth0` on your computer, try the following:

1. click on the `hosts` link in the upper-right-hand corner.
2. add a host.
3. choose the `local` for the host that you're adding.

Let me know if this does the trick.

**Comment by taylorc93** [comment]
@bcoe Thanks for your response.  Unfortunately, that did not fix the problem.  I tried creating a host with `eth0` and got an error saying "no such network interface".

**Comment by bcoe** [comment]
@taylorc93 could you provide some details about the server that you're running on: operating-system, platform (AWS, Digital Ocean, etc).

**Comment by bcoe** [comment]
@taylorc93 it could be the case that eth0 does not exist on the system you are running on.

Try running `ifconfig` to get a list of the network interfaces on your system. Do you see an alternative device that you can use., e.g., `eth1`, `en0`.

**Comment by taylorc93** [comment]
@bcoe, Yep, didn't have `eth0` but had an `eno` interface.  Upon connecting to that, it seems like things are working fine.  Thanks so much for your help!

**Comment by bcoe** [comment]
@taylorc93 awesome \o/ keep me posted with any feedback as you try things out.

**Comment by taylorc93** [comment]
Hey @bcoe, took a bit of a break from this after it looked like it was working for me.  I've managed to get the server set up 100% (all docker containers are running and the service has started).  However, I'm now having an issue logging in via the client.  When I run `npm --verbose login --registry="https://npmclient.cogolo.net:8080" --scope="@cogo", I get this output:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--verbose',
1 verbose cli   'login',
1 verbose cli   '--registry=https://npmclient.cogolo.net:8080',
1 verbose cli   '--scope=@cogo' ]
2 info using npm@2.12.1
3 info using node@v0.12.0
4 verbose adduser before first PUT { _id: 'org.couchdb.user:connor',
4 verbose adduser   name: 'connor',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'connor@cogolabs.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-09-29T15:51:11.495Z' }
5 verbose request uri https://npmclient.cogolo.net:8080/-/user/org.couchdb.user:connor
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 11:51:11 AM
8 verbose request id ecbffc39d1916b7c
9 http request PUT https://npmclient.cogolo.net:8080/-/user/org.couchdb.user:connor
10 info retry will retry, error on last attempt: Error: socket hang up
11 info attempt registry request try #2 at 11:51:21 AM
12 http request PUT https://npmclient.cogolo.net:8080/-/user/org.couchdb.user:connor
13 info retry will retry, error on last attempt: Error: socket hang up
14 info attempt registry request try #3 at 11:52:21 AM
15 http request PUT https://npmclient.cogolo.net:8080/-/user/org.couchdb.user:connor
16 verbose request invalidating /Users/ctaylor/.npm/npmclient.cogolo.net_8080/-/user/org.couchdb.user_3Aconnor on PUT
17 verbose adduser back [ { [Error: socket hang up] code: 'ECONNRESET' },
17 verbose adduser   undefined,
17 verbose adduser   undefined ]
18 verbose stack Error: socket hang up
18 verbose stack     at createHangUpError (_http_client.js:215:15)
18 verbose stack     at TLSSocket.socketOnEnd (_http_client.js:293:23)
18 verbose stack     at TLSSocket.emit (events.js:129:20)
18 verbose stack     at _stream_readable.js:908:16
18 verbose stack     at process._tickCallback (node.js:355:11)
19 verbose cwd /Users/ctaylor/social/scoopfix
20 error Darwin 14.1.0
21 error argv "node" "/usr/local/bin/npm" "--verbose" "login" "--registry=https://npmclient.cogolo.net:8080" "--scope=@cogo"
22 error node v0.12.0
23 error npm  v2.12.1
24 error code ECONNRESET
25 error network socket hang up
25 error network This is most likely not a problem with npm itself
25 error network and is related to network connectivity.
25 error network In most cases you are behind a proxy or have bad network settings.
25 error network
25 error network If you are behind a proxy, please make sure that the
25 error network 'proxy' config is set properly.  See: 'npm help config'
26 verbose exit [ 1, true ]
```
I've also seen this pop up in `/var/log/messages` on the VM, unsure if it's related:
`Sep 29 11:07:23 npmclient nslcd[1149]: [5c55b5] <group/member="root"> ldap_result() failed: Can't contact LDAP server`

I've talked with our system administrators and they don't think that its a networking issue on our end.  Do you have any thoughts on what might be causing this?

**Comment by bcoe** [comment]
Hey @taylorc93 by default the registry URL is http, rather than https:

1. click on the `settings` tab in the admin UI.
2. under `Full URL of npm Enterprise host`, change this to: `http://npmclient.cogolo.net:8080`.
3. login using: `http://npmclient.cogolo.net:8080`.
4. https support will be added soon, but currently the easiest way to do this is to configure it externally, e.g., have an nginx server that redirects https://npmclient.cogolo.net to http://npmclient.cogolo.net:8080.

Let me know if this does the trick for you.

**Comment by taylorc93** [comment]
Yep, that did the trick! Looks like it's totally working now.  Thank you so much for getting back to me so quickly!
