### ISSUE TITLE
Enforce seat limits

### ISSUE THREAD

**Issue by seldo** [npm/npmo-installer#81]
When you buy an X seat license of npmO the license should correctly record the number of seats (if it does not already do so, I forget the implementation of the purchase process). npmO should begin to warn the user when they approach and exceed that limit.

Details TBB (To Be Bikeshedded).

**Comment by bcoe** [comment]
@seldo the warning logic is implemented, and we now have a way of requesting this information from a user. any objection to closing this?

**Comment by seldo** [comment]
Does the current purchase process correctly record the number of seats purchased in the license table? Double check that and then I'm okay to close.

**Comment by bcoe** [comment]
@seldo confirmed that we've stored the appropriate seat counts for all our recent paid customers.
