### ISSUE TITLE
Support for Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by joshblack** [npm/npmo-installer#92]
Currently working with @kevinSuttle to try and install `npmo` on a box running Ubuntu 14.04.3, versus the recommended 14.04.1, and get the following error:

```
W: Failed to fetch http://ppa.launchpad.net/jason-scheunemann/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/jason-scheunemann/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
oh no! something went wrong during the install...
contact support@npmjs.com and we can help get you up and running
```

Is there any way to get the `npmo-installer` working with this patch version of Ubuntu 14.04.3?

As it stands, I installed node v5.0.0 and npm v3.3.6 with nvm and initially ran `npm i -g npmo`, without the `--unsafe` flag, then after realizing my mistake I uninstalled the package globally and ran it again with the `--unsafe` flag with the same failure to fetch error.

**Comment by bcoe** [comment]
`http://ppa.launchpad.net/jason-scheunemann/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages`

Is not used by `node` or the `npmo` installer, it seem like what your have a strange apt source on the server in question.

You might try running:

`apt-get update -y --fix-missing`

npm On-Site will work on Ubuntu 14.04.3.

**Comment by joshblack** [comment]
Yeah, I totally understand that isn't used by either package. Was wondering if I missed something. Looks like the problem is on our end though. That command ends up with the same error message, so will try to investigate further. Thanks for the response!

**Comment by bcoe** [comment]
@joshblack if you look in `/etc/apt/sources.list`, or its subfolders do you happen to see a reference to the `jason-scheunemann` repo?

**Comment by joshblack** [comment]
Yeah, the last entry is:

```
## Uncomment the following two lines to add software from Ubuntu's
## 'extras' repository.
## This software is not part of Ubuntu, but is offered by third-party
## developers who want to ship their latest software.
# deb http://extras.ubuntu.com/ubuntu trusty main
# deb-src http://extras.ubuntu.com/ubuntu trusty main
#Adding repository for lib32stdc++5
deb http://ppa.launchpad.net/jason-scheunemann/ppa/ubuntu trusty main
```

**Comment by joshblack** [comment]
That was it! Going to close this, sorry for the completely random issue and thank you so much for pointing me towards the `/etc/apt/sources.list` file.
